from selenium import webdriver
import time
import sys
browser = webdriver.Firefox()
browser.get('http://www.timvision.it')
accettacookie = browser.find_element_by_id('cookieChoiceDismiss')
type(accettacookie)
accettacookie.click()
accedi = browser.find_element_by_link_text('Accedi')
type(accedi)
accedi.click()
time.sleep(3)
username = browser.find_element_by_id('loginUsernameId')
username.send_keys(sys.argv[1])
pwd =browser.find_element_by_id('loginPwdId')
pwd.send_keys(sys.argv[2])
accedi2 = browser.find_element_by_id('loginBtn')
type(accedi2)
accedi2.click()
time.sleep(3)
browser.get('http://www.timvision.it/detail/'+sys.argv[3])
time.sleep(3)
guarda = browser.find_element_by_link_text('Guarda')
type(guarda)
guarda.click()
